### PR TITLE
Make vpc descriptions consistent

### PR DESCRIPTION
**Pull request by 0xdade**
Didn't change VPC names because I didn't test, just changing the descriptions because they get printed and were inconsistent in formatting. If VPC names can be modified without breaking other things, then I'd be happy to revisit.

### CODE REVIEW

**Comment by tophertimzen** [comment]
This will also need to be changed in all of the Vagrantfiles as they use those names to implement the security group. I'll accept this if we can ensure those are all changed as well. 

```
vpc["security_groups"]["HTTPS From Anywhere"],
```

is currently used on the proxies, for example and this change will break it.

**Comment by 0xdade** [comment]
Why are they using the "description" as an accessor? Isn't that the point of the "name" field?

**Comment by tophertimzen** [comment]
```
     aws.security_groups = [
        vpc["security_groups"]["SSH From COMPANY"],
        vpc["security_groups"]["VPC Allow all traffic"]
      ]
```

Not entirely sure, but the name is used in the Vagrantfiles, not the description.

**Comment by 0xdade** [comment]
That's the description, not the name. 

```
def make_ssh_security(ec2, vpc_id):
    vpc = VPC(ec2, vpc_id,
              name = 'SSH_From_COMPANY',
              desc = 'SSH From COMPANY',
```

**Comment by tophertimzen** [comment]
Once we push the Terraform changes up next week the `make_vpc.py` script will be removed, I am closing this PR as it is no longer relevant to deployment model once we move off of Vagrant.

**Pull request closed without merging**
